name: tania_s_application2
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Mulish
      fonts: 
        - asset: assets/fonts/MulishRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/MulishRomanExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MulishRomanBold.ttf
          weight: 700
        - asset: assets/fonts/MulishRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/MulishRomanLight.ttf
          weight: 300
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoRomanBold.ttf
          weight: 700
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRomanLight.ttf
          weight: 300
        - asset: assets/fonts/RobotoRomanThin.ttf
          weight: 100
